package com.palone.paloneapp.feature_screen_timetable.data.models.responses.ttviewer_autogenerated

data class Defaults(
    val showColors: Boolean,
    val swapAxis: Boolean,
    val timeMode: Boolean
)