package com.palone.paloneapp.feature_screen_timetable.data.models.responses.ttviewer_autogenerated

data class R(
    val _changeEvents: ChangeEvents,
    val allow_my_items: AllowMyItems,
    val current: Current,
    val defaults: Defaults,
    val regular: Regular
)