package com.palone.paloneapp.feature_screen_timetable.data.models.responses.ttviewer_autogenerated

import com.google.gson.annotations.SerializedName

//Autogenerated by JSON to Kotlin Class plugin
data class TtViewerRemoteDataResponse(
    @SerializedName("r")
    val response: R?
)