package com.palone.paloneapp.screen_timetable.data.models.responses.ttviewer_autogenerated

import com.google.gson.annotations.SerializedName

data class ChangeEvents(
    @SerializedName(value = "dbi:global_settings")
    val dbi_global_settings: Int
)