package com.palone.paloneapp.screen_timetable.data.models.responses.ttviewer_autogenerated

data class Timetable(
    val datefrom: String,
    val hidden: Boolean,
    val text: String,
    val tt_num: String,
    val year: Int
)