package com.palone.paloneapp.data.models.responses.ttviewer

import com.google.gson.annotations.SerializedName

//Autogenerated by JSON to Kotlin Class plugin
data class TtViewerRemoteDataResponse(
    @SerializedName("r")
    val response: R
)