package com.palone.paloneapp.timetable.data.models.responses.timetable_autogenerated

import com.google.gson.annotations.SerializedName
import com.palone.paloneapp.models.timetableLessonsResponseData.Ce
import com.palone.paloneapp.models.timetableLessonsResponseData.R

data class TimetableRemoteDataResponse(//Autogenerated, please do not touch
    val ce: Ce,
    @SerializedName("r")
    val response: R
)