package com.palone.paloneapp.timetable.data

import com.palone.paloneapp.data.remote.RetrofitInstance
import com.palone.paloneapp.timetable.data.models.TimetableData
import com.palone.paloneapp.timetable.data.models.responses.ttviewer_autogenerated.TtViewerRemoteDataResponse
import com.palone.paloneapp.utils.timetableDataResponseToListOfTimetableDataParser.TimetableDataResponseToListOfTimetableDataParserInterface
import okhttp3.RequestBody.Companion.toRequestBody
import java.util.*

class TimetableRemoteDataProvider {
    suspend fun getRemoteTtViewerData(): TtViewerRemoteDataResponse {
        return try {
            RetrofitInstance.api.getTtViewerData(
                """{"__args":[null,${
                    Calendar.getInstance().get(Calendar.YEAR)
                }],"__gsh":"00000000"}""".toRequestBody()
            )
        } catch (e: Exception) {
            TtViewerRemoteDataResponse(response = null)
        }

    }

    suspend fun getRemoteTimetableData(
        timetableDataParser: TimetableDataResponseToListOfTimetableDataParserInterface,
        timetableVersion: Int
    ): List<TimetableData> {
        return try {
            timetableDataParser.getTimetableDataResponseParsedToListOfTimetableData(
                RetrofitInstance.api.getTimetableData(
                    """{"__args":[null,"$timetableVersion"],"__gsh":"00000000"}""".toRequestBody()
                )
            )
        } catch (e: Exception) {
            listOf()
        }
    }

}