package com.palone.paloneapp.feature_screen_substitutions.data.models.responses.substitutions_autogenerated

import com.google.gson.annotations.SerializedName

data class SubstitutionsRemoteDataResponse(
    @SerializedName("r")
    val response: String
)